# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

set -o vi

# User specific PS1
export HOST=$(hostname -s)
export PS1='
${BOLD}${PWD}${REG}
${LOGNAME}($HOST):'

# User specific environment and startup programs
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$GOPATH/bin

export EDITOR=vim

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export WORKON_HOME=~/envs
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# Unlimited History!
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%m-%d-%R %r] "

# User specific alias'
alias l='ls -lrth'
alias ll='ls -lh'
alias la='ls -lah'
alias cl='clear'
alias cdscripts='cd ~/scripts'
alias cdgit='cd ~/src'
alias cdsrc='cd ~/src'
alias cditskarma='cd ~/src/itskarma'
alias gs='git status'
