# .bashrc

# vi mode is best mode
set -o vi

# User specific PS1
export HOST=$(hostname -s)
export PS1="
${BOLD}${PWD}${REG}
${LOGNAME}($HOST):"

# User specific environment and startup programs
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin

export EDITOR=vim

# Unlimited History!
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%m-%d-%R %r] "

# User specific alias'
alias l='ls -lrth'
alias ll='ls -lh'
alias la='ls -lah'
alias cl='clear'
alias cdscripts='cd ~/scripts'
alias cdgit='cd ~/src'
alias cdsrc='cd ~/src'
alias cditskarma='cd ~/src/itskarma'
alias cddpb='cd ~/src/deployboard'
alias cddeployboard='cd ~/src/deployboard'
alias gs='git status'
alias gb='git branch'
