--- # Manage homebrew packages using ansible
- hosts: localhost
  tasks:

# Copy config files
  - name: copy bash_profile
    copy: src=files/bash_profile dest=~/.bash_profile
  - name: copy bashrc
    copy: src=files/bashrc dest=~/.bashrc

# Homebrew
  - name: Update homebrew and upgrade all
    homebrew: update_homebrew=yes upgrade_all=yes

  - name: Tap tfswitch
    homebrew_tap: warrensbox/tap/tfswitch
    state: present

  - name: Brew install
    homebrew:
      name:
        - git
#        - gcc
        - ansible
        - jq
        - gpg
        - awscli
      state: latest

  - name: Brew cask install
    homebrew_cask:
      name:
        - atom
        - iterm2
        - visual-studio-code
#       - sequel-pro
#       - psequel
#       - firefox
#       - google-chrome
#       - alfred
#       - dropbox
#       - shiftit
#       - 1password
#       - discord
#       - slack
#       - java
      state: present

# Atom packages
  - name: Install atom packages
    command: apm install {{ item }}
    with_items:
      - vim-mode
      - linter
      - linter-ui-default
      - intentions
      - busy-signal
      - linter-js-yaml
      - linter-jsonlint
      - linter-markdown
      - language-terraform
